name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  fnc_test:
    name: Functional Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: make
      - name: Execute
        run: ./functional-test.sh
      - name: Clean
        run: make fclean

  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker

    steps:
      - uses: actions/checkout@v2
  
      - name: Execute Unit Tests
        run: make tests_run



